default_agent: myagent
agents:
  myagent:
    name: myagent
    language: python
    node_version: '20'
    entrypoint: my_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: .
    aws:
      execution_role: arn:aws:iam::819079555973:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-ef1b693622
      execution_role_auto_create: false
      account: '819079555973'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-819079555973-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: myagent-bHKPpuHli3
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:819079555973:runtime/myagent-bHKPpuHli3
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers:
      - name: github-provider
        arn: arn:aws:bedrock-agentcore:us-east-1:819079555973:token-vault/default/oauth2credentialprovider/github-provider
        type: github
        callback_url: ''
      workload:
        name: myagent-workload
        arn: arn:aws:bedrock-agentcore:us-east-1:819079555973:workload-identity-directory/default/workload-identity/myagent-workload
        return_urls:
        - https://gh-agent-aci-aq6nrmcvn96tycbvhnqjgf.streamlit.app
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
